
lib{toml++}: {hxx ixx}{**}

out_pfx_inc = [dir_path] $out_root/include/
src_pfx_inc = [dir_path] $src_root/include/

export_poptions =

if $config.libtoml__.use_exceptions
{
    export_poptions += -DTOML_EXCEPTIONS
}

lib{toml++}:
{
  cxx.export.poptions = "-I$out_pfx_inc" "-I$src_pfx_inc" $export_poptions
}

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
if $version.pre_release
  lib{toml++}: bin.lib.version = "-$version.project_id"
else
  lib{toml++}: bin.lib.version = "-$version.major.$version.minor"

{hxx ixx}{*}:
{
  install.subdirs = true
}
